### ISSUE TITLE
Set up a production-style staging environment for testing

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#159]
The issues around the recent 2.7.2 release show that we need a production-style environment for testing. I think it would be good for this to be a remotely-hosted staging environment.

Specifically, in [this thread](https://wordpress.org/support/topic/latest-update-caused-my-site-to-note-be-available/) and [this thread](https://wordpress.org/support/topic/last-update-broke-my-website-5/), users reported that their sites were inaccessible due to a fatal error. I tracked the issue down to `wysiwyg.php` and fixed it in 2.7.3, but I missed it originally because on both of the sites that I tested on the fatal error was only shown when viewing the WYSIWYG editor itself.

Production WordPress sites usually (hopefully) lock down entirely in the event of a fatal error being detected anywhere in the site and email the owner to report the issue. We need an environment set up like this to help catch fatal errors happening in obscure parts of the site that we don't manually check. Also, we might be able to use that automated email functionality in #31.

**Comment by markcheret** [comment]
note to self: setup staging website for project access and manual testing

**Comment by markcheret** [comment]
I set it up and sent you @lolzim and @Rumperuu admin accounts

**Comment by lolzim** [comment]
OK, I'm in, thank you !
