### ISSUE TITLE
Set up release workflow

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#30]
https://github.com/10up/action-wordpress-plugin-deploy

**Comment by markcheret** [comment]
Thanks for doing this. I'd love to see this in production, soon.
![bitmoji](https://sdk.bitmoji.com/render/panel/e4f91d37-026a-44d0-91ea-b26cfdaa34a7-6cb30e70-cd74-41f9-9edc-366cf44820fb-v1.png?transparent=1&palette=1&width=246)

**Comment by Rumperuu** [comment]
> Thanks for doing this. I'd love to see this in production, soon.

No problem, and thanks to everyone else for reviewing it.

Once PR #64 is merged I'll close this issue and create a new one for workflow automation. Given we've had a lot of substantial changes in a relatively short amount of time, I'm going to step back for a little bit now that the release helper is finished and give it some time to bed in before starting to automate it.

Hopefully that'll give us time to push a couple of releases using it, which should help to identify any problems and smooth out the whole process. Plus it gives us a chance to focus on some bugfixing and feature requests again as a change of pace from process work.
