### ISSUE TITLE
Remove ‘ManFisher’ and ‘Media Competence Institute’ references

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#34]
The project is no longer under the Media Competence Institute org. (which appears to have been [deleted](https://github.com/media-competence-institute)), so Class names (and a couple of functions) should no longer be prefaced with `MCI_`.

Additionally, there is no mention anywhere in the codebase or Plugin directory about the former ‘ManFisher Media ManuFactory’, and the ManFisher dashboard note currently reads ‘the ManFisher menu Will soon disappear as the company name changed and I believe it's overbearing to have that menu for such a simple function as footnotes’.

The dashboard menu item should be moved under the ‘Settings’ menu and reduced to a single **footnotes** tab rather than the three current ones.

@markcheret to review and approve

**Comment by markcheret** [comment]
I agree with this observation. It's a feature request of mine to have footnotes blend in with the rest of the plugins one might install and find the settings where you expect them. We originally had a bunch of other plugins that were nesting under the same menu item. That is no longer needed.

**Comment by markcheret** [comment]
This calls for splitting up into feasible tasks:
- remove the "ManFisher" menu -> at least minor version release
- refactor MCI_

**Comment by Rumperuu** [comment]
> This calls for splitting up into feasible tasks:
> 
>     * remove the "ManFisher" menu -> at least minor version release
> 
>     * refactor MCI_

Refactoring the `MCI_` will be done as part of #35
