### ISSUE TITLE
Host documentation using GitHub Pages

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#42]
We can host the generated documentation (in `docs/`) on GitHub using [GitHub Pages](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/).

@markcheret looks like only you have access to the ‘Settings’ tab.

**Comment by markcheret** [comment]
What do I need to do?

**Comment by markcheret** [comment]
Done: https://markcheret.github.io/footnotes/

**Comment by markcheret** [comment]
Oh, and it's only hosting the docs on the main branch.
