### ISSUE TITLE
AMP compatibility mode

### ISSUE THREAD

**Issue by pewgeuges** [markcheret/footnotes#48]
After adding hard links in 2.3.0 (2020-12-31), Footnotes is now enabled to become fully AMP compatible thanks to @milindmore22 [code contribution](https://github.com/ampproject/amp-wp/issues/5913#issuecomment-785306933) and @westonruter [code contribution](https://github.com/ampproject/amp-wp/issues/5913#issuecomment-785419655). This release is now fast-tracked and shall be followed by submission to AMP PROJECT / WordPress for testing.

[Description restored to its original state. Please see [#issuecomment-797859947](https://github.com/markcheret/footnotes/issues/48#issuecomment-797859947) for further information.]

**Comment by lolzim** [comment]
\o/

**Comment by pewgeuges** [comment]
Yet CSS tooltips are only part of the solution. The plugin also needs AMP script to expand (and collapse) the reference container, because this is triggered mainly by the first click on a footnote referrer.

Moreover, two bugs have been reported shortly after, requiring bugfix releases 2.5.7 (2021-02-27) and 2.5.8 (2021-02-28). As stated in #50: “The plugin is still so buggy it would be shameless to submit it to AMP-WP as-is even after adding AMP compat.”

**Comment by westonruter** [comment]
> The plugin also needs AMP script to expand (and collapse) the reference container, because this is triggered mainly by the first click on a footnote referrer.

You may not need to use `amp-script` for this. You could alternatively use [`amp-bind`](https://amp.dev/documentation/components/amp-bind/) which would be more lightweight. Another option would be the [`toggleClass` or `toggleVisibility` actions](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/#*-(all-elements)).

**Comment by westonruter** [comment]
A pure CSS-based solution could also be to make use of the `:target` selector, but I'm not clear exactly what is being described here.

**Comment by pewgeuges** [comment]
@westonruter,

> > The plugin also needs AMP script to expand (and collapse) the reference container, because this is triggered mainly by the first click on a footnote referrer.
> 
> You may not need to use `amp-script` for this. You could alternatively use [`amp-bind`](https://amp.dev/documentation/components/amp-bind/) which would be more lightweight. Another option would be the [`toggleClass` or `toggleVisibility` actions](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/#*-(all-elements)).

Thank you; `toggleClass` will probably achieve the effect, because we need to toggle between `display: none` and `display: block` for the footnotes list to completely disappear while collapsed.

> A pure CSS-based solution could also be to make use of the `:target` selector, but I'm not clear exactly what is being described here.

The target is a single footnote number in the list, that is being scrolled to and I see we can have smooth scrolling with the `scrollTo`, only that the position needs to be an integer too. This works with hard links, perhaps we could combine the two.

**Comment by milindmore22** [comment]
It seems the AMP attributes are getting added to non-AMP pages too, in case the site has transitional or reader mode user may find some issues eg: check "References" on non-AMP [page](https://plugins.dev6.rt.gw/2021/04/footnotes-test/)

This can be easily fixed by doing additional check in MCI_Footnotes->register_public
```php
if ( did_action( 'wp' ) && function_exists( 'is_amp_endpoint' ) ) {
	self::$a_bool_amp_enabled = is_amp_endpoint();
}
```
I didn't check the whole codebase but can you please let me know why we need an AMP compatibility checkbox and why can't we conditionally check for the AMP endpoint instead as most of plugins and themes do.

![image](https://user-images.githubusercontent.com/1132541/113731143-26be1c00-9716-11eb-9542-1e9a9c31e9d5.png)

**Comment by markcheret** [comment]
this seems to be ready. Can someone please confirm?

**Comment by Rumperuu** [comment]
> this seems to be ready. Can someone please confirm?

AFAICT, Pew has implemented the `toggleClass` suggestion from https://github.com/markcheret/footnotes/issues/48#issuecomment-799580854 (see `/class/task.php:1977–1982`), but not the endpoint detection suggestion from https://github.com/markcheret/footnotes/issues/48#issuecomment-814193614 yet. I also suspect that #87 result in changes that affect this. It may be worth parking this until after that, and then resubmitting the updated codebase to the AMP-WP team for review?

However, I'm unfortunately not able to contribute further on the AMP compat for [ethical reasons](https://www.eff.org/deeplinks/2020/07/googles-amp-canonical-web-and-importance-web-standards-0).

**Comment by markcheret** [comment]
I'm honestly a fan of optimising load times and prioritising user experience. Apart from that, I opt for parking it and it's also ethically highly questionable. I can't remember asking for AMP compatibility or any of the users.
The ethical drawbacks and [technical restrictions and debt introduced](https://www.searchenginejournal.com/amp-seo-everything-you-need-to-know/375931/#close) aren't worth a lightning bolt on the SERPs, though :)

**Comment by pewgeuges** [comment]
@milindmore22 Excuse me please for failing to respond to your question https://github.com/markcheret/footnotes/issues/48#issuecomment-814193614

I missed the point of the AMP check.

Unintentionally I got this plugin messed up.

Then I got uneasy with this plugin and pulled out.

Now it seems unfixable since 1 week ago I opened a PR https://github.com/markcheret/footnotes/pull/250 as @markcheret invited me to do when I left, but @markcheret does not respond any longer. @markcheret must be waiting for somebody else.
