### ISSUE TITLE
Call to undefined method MCI_Footnotes_Task::wp_head()

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#71]
```
Error message: Uncaught Error: Call to undefined method MCI_Footnotes_Task::wp_head() in [...]/www/wp-content/plugins/footnotes/class/dashboard/subpage-main.php:1354
```

Discovered during #70 , confirmed to be present on the SVN repo. too (i.e., not introduced during the process of syncing this repo. back up with the SVN one). Go to the ‘Quick Start Guide’ tab in the settings menu to replicate.

**Comment by markcheret** [comment]
Is this still an issue? I'm confused by recent email exchanges.

**Comment by Rumperuu** [comment]
> Is this still an issue?

On the `main` branch here, no. However, the change has not been propagated to the SVN repo. yet.

> I'm confused by recent email exchanges.

:mask:
