### ISSUE TITLE
PHP Composer checks fail on GitHub

### ISSUE THREAD

**Issue by markcheret** [markcheret/footnotes#73]
**Describe the bug**

**To Reproduce**
1. Create a pull request

**Expected behavior**
No errors

**Additional context**
PHP Composer check output
    - phpdocumentor/flyfinder 1.0.0 requires php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - phpdocumentor/phpdocumentor v3.0.0 requires phpdocumentor/flyfinder ^1.0 -> satisfiable by phpdocumentor/flyfinder[1.0.0].
    - phpdocumentor/phpdocumentor is locked to version v3.0.0 and an update of this package was not requested.

**Comment by Rumperuu** [comment]
Updating the lockfile doesn't make the build pass, it fails later on. See https://github.com/markcheret/footnotes/pull/70#issue-612951844

> Not sure why the PHP build is failing, the command (`composer install --prefer-dist --no-progress`) works fine when I run it locally. Is there an issue in the preceding caching step (e.g. it hashes the lockfile incorrectly, and then the composer install command can't parse it)?

**Comment by markcheret** [comment]
the composer on the GitHub action uses PHP 8.0.3. The results show that the composer.json calls for PHP 7.0. Not sure how to fix this.
