### ISSUE TITLE
Use file-modified timestamps for stylesheet cache busting

### ISSUE THREAD

**Issue by Rumperuu** [markcheret/footnotes#80]
[`wp_register_style()`](https://developer.wordpress.org/reference/functions/wp_register_style/) can take an optional fourth argument that will override the use of the current WordPress version number as a URL query param appended to each CSS stylesheet , so that browsers will be forced to download new stylesheets rather that using cached old versions.

You can use whatever you want as the fourth argument. Currently (i.e., on the SVN repo.) a constant string named `C_STR_PACKAGE_VERSION` is used, representing the current package (development) version number.

A superior approach is to use `filemtime()` to get the last-modified time of each stylesheet file. This means that, even if a file is modified multiple times during a single version, the cache-busting will still work. This also means we do not have to manually update the string constant, and there is no chance of anyone forgetting to do so.

This change has already been made to the GitHub repo. in https://github.com/markcheret/footnotes/commit/a66faae03d720ea4dadf84b4f1bcf548e9c92502#commitcomment-49511226 — it has not yet been propagated to the SVN repo.

As far as I can tell, there is no compelling reason to prefer the use of the manually-updated package version string constant. If anyone disagrees, please explain why below.

**Comment by markcheret** [comment]
I agree.

**Comment by lolzim** [comment]
ok for me too.

**Comment by pewgeuges** [comment]
In WordPress, proper versioning is done using the release version. 

What we’ll do is change the name from PACKAGE_VERSION to VERSION.

Ultimately I grasp the point of what’s beinng discussed: I picked the wrong version field for the cache busting. 

By no means is this plugin going to release timestamps as version arguments, unlike ALL OTHER plugins and themes.

**Comment by Rumperuu** [comment]
> In WordPress, proper versioning is done using the release version.
> 
> What we’ll do is change the name from PACKAGE_VERSION to VERSION.
> 
> Ultimately I grasp the point of what’s beinng discussed: I picked the wrong version field for the cache busting.
> 
> By no means is this plugin going to release timestamps as version arguments, unlike ALL OTHER plugins and themes.

Could you please present an actual reason for preferring the use of version numbers over timestamps? Or a link to support your claim that ‘proper versioning is done using the release version’ in WordPress?

**Comment by markcheret** [comment]
The point that is being discussed is how footnotes will deal with cache-busting. This is a blameless discussion that has come to a conclusion. WordPress' standard mechanism is using the WordPress version number. That might work for them and their bigger releases. It doesn't work for us as we're releasing more frequently than WordPress does and we want to ensure that site visitors use the latest stylesheets provided by the plugin. We're free to choose what to use. The team has voted.

I summarise: The vote is 3 yay, 1 nay. The yay's have it. So footnotes will use timestamps for cache-busting moving forward.

**Comment by Rumperuu** [comment]
See #83 for submitted changes.
