### ISSUE TITLE
Version 2.5.11 and above disable widget areas in Hueman Theme

### ISSUE THREAD

**Issue by pewgeuges** [markcheret/footnotes#81]
## Bug description

Hueman Theme loses its widget areas when Footnotes 2.6.6 is used, User reported on Support Forum:

https://wordpress.org/support/topic/last-update-make-sidebar-disappear-on-hueman-theme/#post-14318471

Testing showed that all versions above 2.5.10 have this impact.

## Steps to reproduce

Install-activate Hueman theme on WordPress.

Install -activate Footnotes 2.5.10 > works
Install-activate Footnotes 2.5.11 > fails

## Expected
Widget areas display.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by markcheret** [comment]
https://wordpress.org/support/theme/hueman/ are the theme authors

**Comment by markcheret** [comment]
code has already been pushed to SVN, waiting for @pewgeuges to commit it here to also close #99
